# la pipeline s'executera a chaque commit sur master
trigger:
- master

# On specifie le pool a utiliser
pool: "default"

variables:
- name: CloudInitContent

steps:

# Déploiement du azure keyvault et ajout d'un secret dans un ressource groupe dedié
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(1dba5540-2771-4f4f-9434-9f0150a9c88f)'
    subscriptionId: '1dba5540-2771-4f4f-9434-9f0150a9c88f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DACR-RG-KV'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\devoir1\azuredeploykeyvault.json'
    csmParametersFile: '$(Build.SourcesDirectory)\devoir1\azuredeploykeyvault.parameters.json'
    deploymentMode: 'Incremental'
    
# On récupère la valeur du secret dans le keyvault
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azure subscription 1(1dba5540-2771-4f4f-9434-9f0150a9c88f)'
    KeyVaultName: 'DACR-KV-V'
    SecretsFilter: '*'
    RunAsPreJob: false

# script qui va lire et encoder le contenu de 'Cloud-init.xaml'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Import-Module Microsoft.PowerShell.Security
      $CloudContent = Get-Content -Path .\devoir1\Cloud-init.xaml -Raw
      Write-Host $CloudContent
      $encodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))
      Write-Host $encodedContent
      Write-Host "##vso[task.setvariable variable=CloudInitContent;]$encodedContent"
      
# Déploiement du Scale Set
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(1dba5540-2771-4f4f-9434-9f0150a9c88f)'
    subscriptionId: '1dba5540-2771-4f4f-9434-9f0150a9c88f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DACR-RG'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\devoir1\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\devoir1\azuredeploy.parameters.json'
    overrideParameters: '-customData $(CloudInitContent) -adminPassword $(AdminPass)'
    deploymentMode: 'Incremental'
    
