
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: "default"

variables:
- name: CloudInitContent

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(1dba5540-2771-4f4f-9434-9f0150a9c88f)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Creating secret AdminPass in Key Vault..."
      az keyvault secret set --vault-name $(DACR-KV) --name 'AdminPass' --value $(Damiencren###)

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azure subscription 1(1dba5540-2771-4f4f-9434-9f0150a9c88f)'
    keyVaultName: '$(DACR-KV)'
    secretsFilter: 'AdminPass'
    runAsPreJob: true

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Import-Module Microsoft.PowerShell.Security
      $CloudContent = Get-Content -Path .\devoir1\Cloud-init.txt -Raw
      Write-Host $CloudContent
      $encodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))
      Write-Host $encodedContent
      Write-Host "##vso[task.setvariable variable=CloudInitContent;]$encodedContent"
      

- script: |
    echo $(CloudInitContent)

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(1dba5540-2771-4f4f-9434-9f0150a9c88f)'
    subscriptionId: '1dba5540-2771-4f4f-9434-9f0150a9c88f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DACR-RG'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\devoir1\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\devoir1\azuredeploy.parameters.json'
    overrideParameters: '-customData $(CloudInitContent) -adminPassword $(AdminPass)'
    deploymentMode: 'Incremental'
    
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(1dba5540-2771-4f4f-9434-9f0150a9c88f)'
    subscriptionId: '1dba5540-2771-4f4f-9434-9f0150a9c88f'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DACR-RG-KV'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\devoir1\azuredeploykeyvault.json'
    csmParametersFile: '$(Build.SourcesDirectory)\devoir1\azuredeploykeyvault.parameters.json'
    deploymentMode: 'Incremental'